### ISSUE TITLE
Error inflating class com.google.android.exoplayer2.ui.StyledPlayerView

### ISSUE THREAD

**Issue by AndroidLMY** [Leon406/AndResGuard#10]
使用AndResGuard 抛出了该错误如何解决Binary XML file line #81 in com.xg.fazf:layout/item_cp_room_list_game: Binary XML file line #81 in com.xg.fazf:layout/item_cp_room_list_game: Error inflating class com.google.android.exoplayer2.ui.StyledPlayerView

混淆文件也已经添加过 执行完压缩后apk安装出现此问题 没有执行完压缩的包安装一切正常

**Comment by Leon406** [comment]
看下是不是有资源id需要加入白名单,ConstraintLayout需要额外注意
将相关id加入白名单再看看
