### ISSUE TITLE
AGP7.4安装包的时候提示apk非法

### ISSUE THREAD

**Issue by indieexplore** [Leon406/AndResGuard#12]
`resGuard-app.apk: Failure [INSTALL_FAILED_INVALID_APK: INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2]`，有遇到过吗

**Comment by Leon406** [comment]
https://blog.csdn.net/wxz1179503422/article/details/126956265?utm_medium=distribute.pc_relevant.none-task-blog-2~default~baidujs_baidulandingword~default-4-126956265-blog-115173875.235^v38^pc_relevant_sort_base3&spm=1001.2101.3001.4242.3&utm_relevant_index=5

**Comment by indieexplore** [comment]
是的，需要将该属性extractNativeLibs 设置为true，参考：https://github.com/iBotPeaches/Apktool/issues/1626
