### ISSUE TITLE
关于AGP4.2以后支持对资源文件重命名

### ISSUE THREAD

**Issue by zj565061763** [Leon406/AndResGuard#14]
你好，我的使用场景是对资源重命名，提高破解App的门槛。自从AGP4.2以后支持资源文件重命名，是不是意味着对我来说可以不再用AndResGuard了，我对apk大小的要求没那么严格。

**Comment by Leon406** [comment]
` AndResGuard是一个帮助你缩小APK大小的工具，他的原理类似Java Proguard，但是只针对资源。他会将原本冗长的资源路径变短，例如将res/drawable/wechat变为r/d/a。
AndResGuard不涉及编译过程，只需输入一个apk(无论签名与否，debug版，release版均可，在处理过程中会直接将原签名删除)，可得到一个实现资源混淆后的apk(若在配置文件中输入签名信息，可自动重签名并对齐，得到可直接发布的apk)以及对应资源ID的mapping文件。`

可以不用，记得自带的压缩效果不好
