### ISSUE TITLE
agp 7.1+ 不支持

### ISSUE THREAD

**Issue by ucxl** [Leon406/AndResGuard#2]
大神看下错误提示：Cannot convert string value 'UNIFIED_TEST_PLATFORM' to an enum value of type 'com.android.builder.model.AndroidGradlePluginProjectFlags$BooleanFlag' (valid case insensitive values: APPLICATION_R_CLASS_CONSTANT_IDS, TEST_R_CLASS_CONSTANT_IDS, TRANSITIVE_R_CLASS, JETPACK_COMPOSE, ML_MODEL_BINDING)

**Comment by Leon406** [comment]
https://www.jianshu.com/p/60df0c03bbf3
不是项目的问题,是你AGP版本的问题

目前用的AGP 7.3.1
