### ISSUE TITLE
Support AGP 7.4.0

### ISSUE THREAD

**Issue by xDragonZ** [Leon406/AndResGuard#3]
> Caused by: groovy.lang.MissingPropertyException: No such property: variantDslInfo for class: com.android.build.gradle.internal.variant.ApplicationVariantData

https://github.com/Leon406/AndResGuard/blob/73b6c6b8dfa56c41d2ad2408880cf7cc76965b98/AndResGuard-gradle-plugin/src/main/groovy/com/tencent/gradle/AndResGuardTask.groovy#L60

**Comment by ak47king** [comment]
这个我也查了下api，貌似agp7.4.0里边没有这个参数了(已解决，参数变更成variant.component.dslInfo这个了)

**Comment by zhangzhenxi** [comment]
> 这个我也查了下api，貌似agp7.4.0里边没有这个参数了(已解决，参数变更成variant.component.dslInfo这个了)

@ak47king 哥们有时间提个PR？

**Comment by hmy65** [comment]
@Leon406 大佬帮看下呢？感谢。

**Comment by Leon406** [comment]
> @Leon406 大佬帮看下呢？感谢。

maven center 已更新到 1.2.23, 支持AGP 7.4.x
