### ISSUE TITLE
Android Gradle plugin 8.0 不兼容

### ISSUE THREAD

**Issue by hmy65** [Leon406/AndResGuard#6]
“android.enableResourceOptimizations=false”
has been removed in version 8.0 of the Android Gradle plugin.

@Leon406 作者大哥好，8.0 版本的Android Gradle plugin已经没有这个属性了，而且强制使用java17也会导致andresguard问题

**Comment by Leon406** [comment]
要么不要升级AGP, 要么不要用AndResGuard, 用AGP默认的混淆

或者你能找到AGP 8.x 禁用混淆的方法

**Comment by hmy65** [comment]
> 要么不要升级AGP, 要么不要用AndResGuard, 用AGP默认的混淆
> 
> 或者你能找到AGP 8.x 禁用混淆的方法

有没有办法先兼容一下jdk17呢 作者大哥

**Comment by Leon406** [comment]
搞不动了, 重新签名有问题,暂时无法解决, 可以尝试通过命令行工具解决

**Comment by hmy65** [comment]
@Leon406 感觉可以archive repo了，很难找到接手人
